service: serverless-haskell-example

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

functions:
  hello:
    handler: serverless-haskell-example.example-exe
  apigw:
    handler: serverless-haskell-example.api-exe
    events:
      - http:
          path: hello/{name}
          method: get

plugins:
  - serverless-haskell

custom:
  haskell:
    # Always recommended to set this to avoid incompatibility issues with
    # dependent system libraries.
    docker: true
