service: NAME

provider:
  name: aws
  runtime: nodejs8.10

functions:
  main:
    handler: shtest.main

  subdir:
    handler: subdir/subtest.main

plugins:
- serverless-haskell

custom:
  haskell:
    arguments:
      NAME:
      - one
      - two
      - --three
    docker: DOCKER
    extraLibraries:
    - libpcre.so.3
