name:                serverless-haskell-apigw-example
category:            AWS, Cloud, Network
maintainer:          doverton@seek.com.au
version:             1.0.0
github:              seek-oss/serverless-haskell
license:             MIT
synopsis:            Deploying Haskell code onto AWS APIGateway and Lambda using Serverless
description:         Example package to demonstrate deployment of Haskell code onto AWS APIGateway and Lambda using Serverless

dependencies:
- base >= 4.7 && < 5

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - lens
    - serverless-haskell
    - text
    - unordered-containers
