service: serverless-haskell-apigw-example

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  hello:
    handler: serverless-haskell-apigw-example.api-exe
    events:
      - http:
          path: hello/{name}
          method: get

plugins:
  - serverless-haskell
