name: subtest
version: 0.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- serverless-haskell
- text

executables:
  main:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
